<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1KDN3d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1KDN3d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA1KDN3d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA1KDN3d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA1KDN3d\App_KernelDevDebugContainer([
    'container.build_hash' => 'A1KDN3d',
    'container.build_id' => '952d15fb',
    'container.build_time' => 1593777309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1KDN3d');
