<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxwGNYQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxwGNYQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxwGNYQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxwGNYQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZxwGNYQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZxwGNYQ',
    'container.build_id' => 'c82601f8',
    'container.build_time' => 1593769484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxwGNYQ');
