<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYixAGAb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYixAGAb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYixAGAb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYixAGAb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYixAGAb\App_KernelDevDebugContainer([
    'container.build_hash' => 'YixAGAb',
    'container.build_id' => 'b2c20f79',
    'container.build_time' => 1593781750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYixAGAb');
